version: "3.3"

services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - "jenkins_home:/var/jenkins_home"
volumes:
  jenkins_home:

